name: Report Card
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Get Go report card
      uses: creekorful/goreportcard-action@v1.0
      with:
        args: ./...

 

